name: Deploying Webpage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
    web-app-pull:
        name: Pull File From Github
        runs-on: ubuntu-latest
        steps:
            - name: Pulling code from Github
              uses: actions/checkout@v4
              with:
                ref: master

            - name: Checking pulled files
              run: ls -al