name: Deploying Webpage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  push: 
    branches: master
jobs:
    web-app-pull:
        name: Pull File From Github
        runs-on: ubuntu-latest
        steps:
            - name: Pulling code from Github
              uses: actions/checkout@v4
              with:
                ref: master
            
            - name: Checking Variable
              run: echo $GITHUB_RUN_ATTEMPT

            # - name: Copy files to Server
            #   uses: appleboy/scp-action@v0.1.7
            #   with:
            #     host: ${{ secrets.HOST }}
            #     username: ${{ secrets.USER }}
            #     key: ${{ secrets.KEY }}
            #     source: index.html
            #     target: webpage
            
            # - name: Updating Index file
            #   uses: appleboy/ssh-action@v1.1.0
            #   with:
            #     host: ${{ secrets.HOST }}
            #     username: ${{ secrets.USER }}
            #     key: ${{ secrets.KEY }}
            #     script: |
            #       sudo mv webpage/index.html /var/www/html/webpage/
            #       sudo systemctl restart nginx