name: Deploying Webpage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
    web-app-deploy:
        name: Pull File From Github
        runs-on: ubuntu
        steps:
            - uses: actions/checkout@v4
              with:
                ref: master
            