name: Deploying Webpage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
    web-app-pull:
        name: Pull File From Github
        runs-on: ubuntu
        steps:
            - name: Pulling code from Github
              uses: actions/checkout@v4
              with:
                ref: master
    web-app-check:
        name: Checking pulled files
        runs-on: ubuntu
        steps:
            - run: ls -al